# Script to perform LLC extractions
apiVersion: batch/v1
kind: Job
metadata:
  name: xavier-deimos-v0
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: container
        image: localhost:30081/profxj/pypeit:latest  # UPDATE
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1"
            memory: "16Gi"
            ephemeral-storage: 64Gi
          limits:
            cpu: "1"
            memory: "32Gi"
            ephemeral-storage: 150Gi
            #nvidia.com/gpu:  "1"  # See docs to exlude certain types
            # https://ucsd-prp.gitlab.io/userdocs/running/gpu-pods/
        command: ["/bin/bash", "-c"]
        args:
          - sleep 600;
            cd PypeIt;  
            git checkout develop; 
            cd ..;
            git clone https://github.com/pypeit/adap.git;
            git checkout starting_up; 
            git pull; 
            cd ..;
            mkdir foo;
            cd foo;
            aws --endpoint http://rook-ceph-rgw-nautiluss3.rook s3 get s3://pypeit/RAW_DATA/keck_deimos/830G_LVM_8400 --recursive --force;
            cd kube_tests;
            source ~/adap/kube_tests/deimos_fun.src;
            #cd ..;
            #aws --endpoint http://rook-ceph-rgw-nautiluss3.rook s3 cp foo s3://llc --recursive --force;
        env:
          - name: "ENDPOINT_URL"
            value: "http://rook-ceph-rgw-nautiluss3.rook"
          - name: "S3_ENDPOINT"
            value: "rook-ceph-rgw-nautiluss3.rook"
        volumeMounts:
          - name: prp-s3-credentials
            mountPath: "/root/.aws/credentials"
            subPath: "credentials"
          - name: ephemeral
            mountPath: "/tmp"
          - name: "dshm"
            mountPath: "/dev/shm"
      nodeSelector:
        nautilus.io/disktype: nvme
        gpu-type: "1080Ti"  # titan-xp
      restartPolicy: Never
      volumes:
        # Secrets file for nautilus s3 credentials .aws/credentials and .s3cfg
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
        # Shared memory (necessary for Python's multiprocessing.shared_memory module to work)
        - name: dshm
          emptyDir:
            medium: Memory
        # Ephemeral storage
        - name: ephemeral
          emptyDir: {}
