apiVersion: batch/v1
kind: Job
metadata:
  name: adap2020-flux-from-queue
spec:
  backoffLimit: 2
  parallelism: 2
  template:
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: flux-worker
        args:
        - source /home/pypeitusr/pypeit_env/bin/activate; pip install redis boto3 google-api-python-client gspread;  
          cd /home/pypeitusr/PypeIt; git fetch; git checkout hires_flux_coadd1d; git pull;
          pip install -e '.[dev]'; export PYPEIT_COMMIT=`git log -n 1 | head -n 1 | cut -c 8-47`; 
          echo $PYPEIT_COMMMIT; 
          cd /tmp; mkdir adap_root; cd adap_root;
          pip install gspread; git clone https://github.com/pypeit/adap.git; cd adap; git checkout adap_2020;
          aws --endpoint $ENDPOINT_URL s3 cp --no-progress s3://pypeit/adap/scripts_2020/ scripts/ --recursive;
          aws --endpoint $ENDPOINT_URL s3 cp --no-progress s3://pypeit/adap/config_2020/ config/ --recursive;
          python scripts/flux_coadd1d_from_queue.py --rclone_conf config/rclone.conf --adap_root_dir /tmp/adap_root key=1TADKd3OgbA-2U80iiw2dIxIiNXoF0_z_CJ9VZ9_iek4/WorkQueue redis://10.244.145.213:6379 adap_2020 s3;
          aws --endpoint $ENDPOINT_URL s3 cp --no-progress flux_coadd1d_from_queue.log s3://pypeit/adap/results/${POD_NAME}.log
        command:
        - /bin/bash
        - -c
        image: gitlab-registry.nrp-nautilus.io/dustyreichwein/pypeitcontainers/pypeit:develop
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '1.5'
            ephemeral-storage: 40Gi
            memory: 16Gi
          requests:
            cpu: '1.5'
            ephemeral-storage: 40Gi
            memory: 16Gi
        volumeMounts:
        - mountPath: /home/pypeitusr/.config/gspread/service_account.json
          name: gcloud-service-account
          subPath: credentials
        - mountPath: /tmp
          name: ephemeral
        - mountPath: /home/pypeitusr/.aws/credentials
          name: prp-s3-credentials
          subPath: credentials
        env:
           - name: POD_NAME
             valueFrom:
                fieldRef:
                   fieldPath: metadata.name
           - name: ENDPOINT_URL
             value: http://rook-ceph-rgw-nautiluss3.rook
           - name: S3_ENDPOINT
             value: rook-ceph-rgw-nautiluss3.rook
           - name: DEBIAN_FRONTEND
             value: noninteractive
           - name: QT_QPA_PLATFORM
             value: offscreen
      restartPolicy: Never
      volumes:
      - name: gcloud-service-account
        secret:
          secretName: adap-scorecard-gcloud
      - name: prp-s3-credentials
        secret:
          secretName: prp-s3-credentials            
      - emptyDir: {}
        name: ephemeral
