apiVersion: batch/v1
kind: Job
metadata:
  name: adap-run-scorecard-on-queue
spec:
  backoffLimit: 2
  parallelism: 5
  template:
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: scorecard-worker
        args:
        - apt-get -y update; apt-get install -y rclone; pip install redis awscli boto3 google-api-python-client psutil gspread;  
          cd /home/pypeitusr/PypeIt; git fetch; git checkout b8455e6593aeb6a2d55bdd2d2ad3f62c5fbe4733; ; 
          pip install -e '.[dev]'; export PYPEIT_COMMIT=`git log -n 1 | head -n 1 | cut -c 8-47`; 
          cd /tmp; mkdir adap_root; cd adap_root;
          git clone https://github.com/pypeit/adap.git; cd adap; git checkout adap_2019;
          aws --endpoint $ENDPOINT_URL s3 cp --no-progress s3://pypeit/adap/scripts_2019/ scripts/ --recursive;
          aws --endpoint $ENDPOINT_URL s3 cp --no-progress s3://pypeit/adap/config_2019/ config/ --recursive;
          python scripts/run_scorecard_on_queue.py --rclone_conf config/rclone.conf --adap_root_dir /tmp/adap_root Scorecard/WorkQueue redis://10.244.102.107:6379 adap_2019 s3;
          aws --endpoint $ENDPOINT_URL s3 cp --no-progress scorecard_from_queue.log s3://pypeit/adap/results/${POD_NAME}.log
        command:
        - /bin/bash
        - -c
        image: gitlab-registry.nrp-nautilus.io/dustyreichwein/pypeitcontainers/pypeit:develop
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '1.5'
            ephemeral-storage: 100Gi
            memory: 48Gi
          requests:
            cpu: '1'
            ephemeral-storage: 70Gi
            memory: 32Gi
        volumeMounts:
        - mountPath: /root/.config/gspread/service_account.json
          name: gcloud-service-account
          subPath: credentials
        - mountPath: /tmp
          name: ephemeral
        - mountPath: /root/.aws/credentials
          name: prp-s3-credentials
          subPath: credentials
        env:
           - name: POD_NAME
             valueFrom:
                fieldRef:
                   fieldPath: metadata.name
           - name: ENDPOINT_URL
             value: http://rook-ceph-rgw-nautiluss3.rook
           - name: S3_ENDPOINT
             value: rook-ceph-rgw-nautiluss3.rook
           - name: DEBIAN_FRONTEND
             value: noninteractive
           - name: QT_QPA_PLATFORM
             value: offscreen
      restartPolicy: Never
      volumes:
      - name: gcloud-service-account
        secret:
          secretName: adap-scorecard-gcloud
      - name: prp-s3-credentials
        secret:
          secretName: prp-s3-credentials            
      - emptyDir: {}
        name: ephemeral
