apiVersion: batch/v1
kind: Job
metadata:
  name: adap-reduce-from-queue
spec:
  backoffLimit: 2
  parallelism: 6
  template:
    spec:
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: reduce-worker
        args:
        - source /home/pypeitusr/pypeit_env/bin/activate; pip install boto3 google-api-python-client gspread;  
          cd /home/pypeitusr/PypeIt; git fetch; git checkout order_sync; git pull;
          pip install -e '.[dev]'; export PYPEIT_COMMIT=`git log -n 1 | head -n 1 | cut -c 8-47`; 
          echo $PYPEIT_COMMMIT; 
          cd /tmp; mkdir adap_root; cd adap_root;
          pip install gspread; git clone https://github.com/pypeit/adap.git; cd adap; git checkout adap_2020;
          aws --endpoint $ENDPOINT_URL s3 cp --no-progress s3://pypeit/adap/scripts/ scripts/ --recursive;
          python scripts/reduce_from_queue.py --adap_root_dir /tmp/adap_root --spec keck_hires --scorecard_max_age 7 key=1TADKd3OgbA-2U80iiw2dIxIiNXoF0_z_CJ9VZ9_iek4/WorkQueue /work_queue/work_queue.csv -- -o;
          echo $PYPEIT_COMMMIT >> reduce_from_queue.log; du -sh /tmp >> reduce_from_queue.log; tail -2 reduce_from_queue.log; 
          aws --endpoint $ENDPOINT_URL s3 cp --no-progress reduce_from_queue.log s3://pypeit/adap/results/${POD_NAME}.log
        command:
        - /bin/bash
        - -c
        image: gitlab-registry.nrp-nautilus.io/dustyreichwein/pypeitcontainers:develop
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '1.5'
            ephemeral-storage: 20Gi
            memory: 16Gi
          requests:
            cpu: '1.5'
            ephemeral-storage: 20Gi
            memory: 16Gi
        volumeMounts:
        - mountPath: /home/pypeitusr/.config/gspread/service_account.json
          name: gcloud-service-account
          subPath: credentials
        - mountPath: /work_queue
          name: work-queue
        - mountPath: /tmp
          name: ephemeral
        - mountPath: /home/pypeitusr/.aws/credentials
          name: prp-s3-credentials
          subPath: credentials
        env:
           - name: POD_NAME
             valueFrom:
                fieldRef:
                   fieldPath: metadata.name
           - name: ENDPOINT_URL
             value: http://rook-ceph-rgw-nautiluss3.rook
           - name: S3_ENDPOINT
             value: rook-ceph-rgw-nautiluss3.rook
           - name: DEBIAN_FRONTEND
             value: noninteractive
           - name: QT_QPA_PLATFORM
             value: offscreen
      nodeSelector:
        nautilus.io/disktype: nvme
      restartPolicy: Never
      volumes:
      - name: gcloud-service-account
        secret:
          secretName: adap-scorecard-gcloud
      - name: work-queue
        persistentVolumeClaim:
            claimName: pypeit-adap-work-queue
      - name: prp-s3-credentials
        secret:
          secretName: prp-s3-credentials            
      - emptyDir: {}
        name: ephemeral
