apiVersion: batch/v1
kind: Job
metadata:
  name: adap-init-workqueue
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - args:
        - apt-get update;  pip install gspread; apt-get install -y git; git clone https://github.com/pypeit/adap.git; cd adap; git checkout adap_2020;
          aws --endpoint $ENDPOINT_URL s3 cp --no-progress s3://pypeit/adap/scripts/ scripts/ --recursive;
          python scripts/download_work_queue_from_gs.py "key=1TADKd3OgbA-2U80iiw2dIxIiNXoF0_z_CJ9VZ9_iek4/WorkQueue" /work_queue/work_queue.csv
        command:
        - /bin/bash
        - -c
        image: docker.io/profxj/pypeit_v1@sha256:a2f91f18fb33119a7f08d804dd3259118e0e934612c3868df58f434e3d980740
        imagePullPolicy: Always
        name: container
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: '1'
            memory: 1Gi
        volumeMounts:
        - mountPath: /root/.config/gspread/service_account.json
          name: gcloud-service-account
          subPath: credentials
        - mountPath: /work_queue
          name: work-queue
        - mountPath: /root/.aws/credentials
          name: prp-s3-credentials
          subPath: credentials
        env:
          - name: ENDPOINT_URL
            value: http://rook-ceph-rgw-nautiluss3.rook
      nodeSelector:
        nautilus.io/disktype: nvme
      restartPolicy: Never
      volumes:
      - name: gcloud-service-account
        secret:
          secretName: adap-scorecard-gcloud
      - name: work-queue
        persistentVolumeClaim:
            claimName: pypeit-adap-work-queue
      - name: prp-s3-credentials
        secret:
          secretName: prp-s3-credentials            
