apiVersion: batch/v1
kind: Job
metadata:
  name: adap-refresh-workqueue
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - args:
        - apt-get update;  pip install gspread; apt-get install -y git; git clone https://github.com/pypeit/adap.git; cd adap; git checkout adap_2020;
          python scripts/download_work_queue_from_gs.py --refresh "key=1TADKd3OgbA-2U80iiw2dIxIiNXoF0_z_CJ9VZ9_iek4/WorkQueue" /work_queue/work_queue_2020.csv;
          chown 1001:1001 /work_queue/work_queue_2020.csv; ls -l /work_queue;
        command:
        - /bin/bash
        - -c
        image: docker.io/library/python:3.12
        imagePullPolicy: Always
        name: container
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: '1'
            memory: 1Gi
        volumeMounts:
        - mountPath: /root/.config/gspread/service_account.json
          name: gcloud-service-account
          subPath: credentials
        - mountPath: /work_queue
          name: work-queue
        - mountPath: /root/.aws/credentials
          name: prp-s3-credentials
          subPath: credentials
      nodeSelector:
        nautilus.io/disktype: nvme
      restartPolicy: Never
      volumes:
      - name: gcloud-service-account
        secret:
          secretName: adap-scorecard-gcloud
      - name: work-queue
        persistentVolumeClaim:
            claimName: pypeit-adap-work-queue
      - name: prp-s3-credentials
        secret:
          secretName: prp-s3-credentials            
