apiVersion: apps/v1
kind: Deployment
metadata:
  name: adap-workqueue
  labels:
    k8s-app: adap-workqueue
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: adap-workqueue
  template:
    metadata:
      labels:
        k8s-app: adap-workqueue
    spec:
      containers:
      - name: workqueue
        image: gitlab-registry.nrp-nautilus.io/dustyreichwein/pypeitcontainers/workqueue/pypeit_workqueue_redis
        resources:
           limits:
             memory: 500Mi
             cpu: 1
           requests:
             memory: 100Mi
             cpu: 1
        command: ["redis-server"]