apiVersion: batch/v1
kind: Job
metadata:
  name: adap2023-reduce-from-queue
spec:
  backoffLimit: 1
  parallelism: 2
  template:
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: reduce-worker
        args:
        - source /home/pypeitusr/pypeit_env/bin/activate;
          cd /home/pypeitusr/PypeIt; git fetch; git checkout lris_adap; git pull;
          pip install --no-build-isolation -e '.[dev]'; export PYPEIT_COMMIT=`git log -n 1 | head -n 1 | cut -c 8-47`; 
          echo $PYPEIT_COMMMIT; 
          cd /tmp; mkdir adap_root; cd adap_root;
          git clone https://github.com/pypeit/adap.git; cd adap; git checkout adap_2023;
          aws --endpoint $ENDPOINT_URL s3 cp --no-progress s3://pypeit/adap/scripts_2023/ scripts/ --recursive;
          aws --endpoint $ENDPOINT_URL s3 cp --no-progress s3://pypeit/adap/config_2023/ config/ --recursive;
          python scripts/reduce_from_queue.py --rclone_conf config/rclone.conf --adap_root_dir /tmp/adap_root --scorecard_max_age 7 key=15ealTQOBLB0I_BD-ZiN0lVeP1vt5P9oeGeiWOPN4bq0/WorkQueue redis://adap-workqueue:6379 adap_2023 s3;
          echo $PYPEIT_COMMMIT >> reduce_from_queue.log; du -sh /tmp >> reduce_from_queue.log; tail -2 reduce_from_queue.log; 
          aws --endpoint $ENDPOINT_URL s3 cp --no-progress reduce_from_queue.log s3://pypeit/adap/results/${POD_NAME}.log
        command:
        - /bin/bash
        - -c
        image: gitlab-registry.nrp-nautilus.io/bradh/pypeitcontainers/pypeit_lris_adap:adap_2023
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '1.5'
            ephemeral-storage: 20Gi
            memory: 16Gi
          requests:
            cpu: '1.5'
            ephemeral-storage: 20Gi
            memory: 16Gi
        volumeMounts:
        - mountPath: /home/pypeitusr/.config/gspread/service_account.json
          name: gcloud-service-account
          subPath: credentials
        - mountPath: /tmp
          name: ephemeral
        - mountPath: /home/pypeitusr/.aws/credentials
          name: prp-s3-credentials
          subPath: credentials
        env:
           - name: POD_NAME
             valueFrom:
                fieldRef:
                   fieldPath: metadata.name
           - name: ENDPOINT_URL
             value: http://rook-ceph-rgw-nautiluss3.rook
           - name: S3_ENDPOINT
             value: rook-ceph-rgw-nautiluss3.rook
           - name: DEBIAN_FRONTEND
             value: noninteractive
           - name: QT_QPA_PLATFORM
             value: offscreen
      restartPolicy: Never
      volumes:
      - name: gcloud-service-account
        secret:
          secretName: adap23-scorecard-gcloud
      - name: prp-s3-credentials
        secret:
          secretName: prp-s3-credentials            
      - emptyDir: {}
        name: ephemeral
