apiVersion: batch/v1
kind: Job
metadata:
  name: adap-sync-backups-from-queue
spec:
  backoffLimit: 2
  parallelism: 5
  template:
    spec:
      containers:
      - name: sync-worker
        args:
        - apt-get -y update; apt-get install -y rclone; pip install awscli boto3 google-api-python-client psutil; 
          cd /tmp; mkdir adap_root; cd adap_root;
          pip install gspread==5.6.2; git clone https://github.com/pypeit/adap.git; cd adap; git checkout utils_test;
          aws --endpoint $ENDPOINT_URL s3 cp --no-progress s3://pypeit/adap/scripts/ scripts/ --recursive;
          python scripts/sync_backup_from_queue.py --adap_root_dir /tmp/adap_root --rclone_conf /tmp/adap_root/adap/config/rclone.conf Scorecard/WorkQueue /work_queue/work_queue.csv;
          aws --endpoint $ENDPOINT_URL s3 cp --no-progress sync_from_queue.log s3://pypeit/adap/results/${POD_NAME}.log
        command:
        - /bin/bash
        - -c
        image: localhost:30081/profxj/pypeit_v1:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '1.5'
            ephemeral-storage: 100Gi
            memory: 8Gi
          requests:
            cpu: '1'
            ephemeral-storage: 100Gi
            memory: 8Gi
        volumeMounts:
        - mountPath: /root/.config/gspread/service_account.json
          name: gcloud-service-account
          subPath: credentials
        - mountPath: /work_queue
          name: work-queue
        - mountPath: /tmp
          name: ephemeral
        - mountPath: /root/.aws/credentials
          name: prp-s3-credentials
          subPath: credentials
        env:
           - name: POD_NAME
             valueFrom:
                fieldRef:
                   fieldPath: metadata.name
           - name: ENDPOINT_URL
             value: http://rook-ceph-rgw-nautiluss3.rook
           - name: S3_ENDPOINT
             value: rook-ceph-rgw-nautiluss3.rook
           - name: DEBIAN_FRONTEND
             value: noninteractive
           - name: QT_QPA_PLATFORM
             value: offscreen
      nodeSelector:
        nautilus.io/disktype: nvme
      restartPolicy: Never
      volumes:
      - name: gcloud-service-account
        secret:
          secretName: adap-scorecard-gcloud
      - name: work-queue
        persistentVolumeClaim:
            claimName: pypeit-adap-work-queue
      - name: prp-s3-credentials
        secret:
          secretName: prp-s3-credentials            
      - emptyDir: {}
        name: ephemeral
