apiVersion: batch/v1
kind: Job
metadata:
  name: adap-reduce-one
spec:
  backoffLimit: 2
  parallelism: 1
  template:
    spec:
      containers:
      - name: reduce-worker
        args:
        - apt-get -y update; apt-get install -y rclone; pip install awscli boto3 google-api-python-client psutil;  cd PypeIt; git fetch;
          git checkout 1.13.0;
          pip install -e '.[dev,bottleneck]'; export PYPEIT_COMMIT=`git log -n 1 | head -n 1 | cut -c 8-47`; 
          cd /tmp; 
          echo "${DATASET},IN QUEUE" > work_queue.csv;
          mkdir adap_root; cd adap_root;
          pip install gspread==5.6.2; git clone https://github.com/pypeit/adap.git; cd adap; git checkout main;
          aws --endpoint $ENDPOINT_URL s3 cp --no-progress s3://pypeit/adap/scripts/ scripts/ --recursive;
          python scripts/reduce_from_queue.py WorkQueueTest/WorkQueue /tmp/work_queue.csv --adap_root_dir /tmp/adap_root --scorecard_max_age 100;
          du -sh /tmp >> reduce_from_queue.log; tail -1 reduce_from_queue.log;
          aws --endpoint $ENDPOINT_URL s3 cp --no-progress reduce_from_queue.log s3://pypeit/adap/results/${POD_NAME}.log
        command:
        - /bin/bash
        - -c
        image: docker.io/profxj/pypeit_v1@sha256:a2f91f18fb33119a7f08d804dd3259118e0e934612c3868df58f434e3d980740
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '1.5'
            ephemeral-storage: 100Gi
            memory: 48Gi
          requests:
            cpu: '1'
            ephemeral-storage: 100Gi
            memory: 32Gi
        volumeMounts:
        - mountPath: /root/.config/gspread/service_account.json
          name: gcloud-service-account
          subPath: credentials
        - mountPath: /tmp
          name: ephemeral
        - mountPath: /root/.aws/credentials
          name: prp-s3-credentials
          subPath: credentials
        env:
           - name: POD_NAME
             valueFrom:
                fieldRef:
                   fieldPath: metadata.name
           - name: ENDPOINT_URL
             value: http://rook-ceph-rgw-nautiluss3.rook
           - name: S3_ENDPOINT
             value: rook-ceph-rgw-nautiluss3.rook
           - name: DEBIAN_FRONTEND
             value: noninteractive
           - name: QT_QPA_PLATFORM
             value: offscreen
           - name: DATASET
             value: gn+40_oct_reduce/600ZD_7350_GG495/2012-12-16_2012-12-18
      nodeSelector:
        nautilus.io/disktype: nvme
      restartPolicy: Never
      volumes:
      - name: gcloud-service-account
        secret:
          secretName: adap-scorecard-gcloud
      - name: prp-s3-credentials
        secret:
          secretName: prp-s3-credentials            
      - emptyDir: {}
        name: ephemeral
