apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pypeit-adap-work-queue
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi    
  storageClassName: rook-cephfs
